org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.builtInKotlin=false
android.suppressUnsupportedCompileSdk=36
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE
org.gradle.java.home=C:\\Projects\\Android\\sad\\.tools\\jdk-17
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.paths=C:\\Projects\\Android\\sad\\.tools\\jdk-17
