plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.yulancer.sad'
    compileSdk 37

    defaultConfig {
        applicationId "ru.yulancer.sad"
        minSdk 21
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.13.2'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.fragment:fragment:1.8.9'
    implementation 'com.github.infiniteautomation:modbus4j:3.1.0'
    implementation 'net.danlew:android.joda:2.14.2.1'
}
